services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8001:8001" # Example port mapping, adjust as needed
  directus:
    image: directus/directus:latest
    environment:
      KEY: ${KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SEARCH_PATH: ${DB_SEARCH_PATH}
    ports:
      - "8055:8055"
